
export const PRODUCTOR_FETCHING =  "PRODUCTOR_FETCHING";
export const PRODUCTOR_SSUCCESS =  "PRODUCTOR_SSUCCESS"
export const PRODUCTOR_FAILED =  "PRODUCTOR_FAILED"
export const PRODUCTOR_SINGAL_FETCHING =  "PRODUCTOR_SINGAL_FETCHING";
export const PRODUCTOR_SINGAL_SSUCCESS =  "PRODUCTOR_SINGAL_SSUCCESS"
export const PRODUCTOR_SINGAL_FAILED =  "PRODUCTOR_SINGAL_FAILED"